version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:80:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - geocache-network
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - geocache-network
    volumes:
      - redis-data:/data

networks:
  geocache-network:
    name: geocache-network
    external: true

volumes:
  redis-data:
