apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-cache
  labels:
    app: geo-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geo-cache
  template:
    metadata:
      labels:
        app: geo-cache
    spec:
      containers:
      - name: geo-cache
        image: geo-cache:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
